system:
  name: "Crypto Investment Analyst"
  version: "1.0.0"
  debug: false

llm:
  provider: "anthropic"  # or "openai"
  model: "claude-3-sonnet-20240229"
  temperature: 0.1
  max_tokens: 4000

agents:
  memory:
    enabled: true
    max_messages: 50

  technical_analysis:
    enabled: true
    confidence_threshold: 0.7

  onchain_analysis:
    enabled: true
    confidence_threshold: 0.6

  defi_fundamentals:
    enabled: true
    confidence_threshold: 0.7

  sentiment_fusion:
    enabled: true
    confidence_threshold: 0.5

apis:
  rate_limits:
    coingecko: (30, 'min')  # requests per minute
    etherscan: (5, 's')   # requests per second
    serper: ('100', 'hr')    # requests per hour
    reddit: ('60', 'min')     # requests per minute

  timeouts:
    default: 30    # seconds

cryptocurrencies:
  focus: ["bitcoin", "ethereum"]
  symbols: ["BTC", "ETH"]

analysis:
  timeframes: ["1h", "4h", "1d", "1w"]
  technical_indicators:
    - "RSI"
    - "MACD"
    - "Moving_Averages"
    - "Bollinger_Bands"
    - "Volume"